### ISSUE TITLE
The implement of bi-directional self-attention in the last layer of Qwen2-vl

### ISSUE THREAD

**Issue by szlll** [TempleX98/EasyRef#2]
Thanks for your great work!
However,  I have a question regarding your paper where you mention "adopt bi-directional self-attention to facilitate the propagation of representations across the reference images in the final layer." However, in the code you have provided, I seem unable to find the related modifications:
`mllm_final_layer = mllm_final_layer.model`
`mllm_final_layer.layers = mllm_final_layer.layers[-1:]`
`mllm_final_layer.embed_tokens = torch.nn.Identity()`
`mllm_final_layer.visual = torch.nn.Identity()`
`mllm_final_layer.lm_head = torch.nn.Identity()`
`mllm_final_layer.reference_tokens = torch.nn.Parameter(0.1 * torch.randn(num_tokens, mllm_final_layer.config.hidden_size))`
`self.mllm_final_layer = mllm_final_layer.to(self.device)` 
It appears that the final layer is used directly without modifications to the attention mechanism. Could you please clarify this for me?
Thank you for your time and assistance.

**Comment by TempleX98** [comment]
Thank you for your feedback! The bidirectional attention code can be found [here](https://github.com/TempleX98/EasyRef/blob/30433d1e123e3c242689685344034e0fdddc86bb/finetune_sdxl.py#L373). I realized I forgot to include it in the model implementation in the released code. This has now been fixed in the latest commit.

**Comment by szlll** [comment]
Thanks for your response! Your work is invaluable, and I am grateful for your support.
